import = ["~/.config/alacritty/catppuccin_macchiato.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font Propo"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Propo"
style = "Bold"

[font.italic]
family = "IBM Plex Mono"
style = "Italic"

[font.bold_italic]
family = "IBM Plex Mono"
style = "Bold Italic"

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.9
decorations = "Full"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
