# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# status-line
set -g status-style bg=default,fg=default

set -g status-left '#[fg=green][#S] '
set -g status-left-length 20

set -g status-right '%Y-%m-%d %H:%M'
set -g status-right-length 50

set -g window-status-current-style bg=cyan,fg=black