term xterm-kitty

include matugen.conf
background_opacity 0.8

# font
font_family       FiraCode Nerd Font
bold_font         auto
italic_font       BlexMono Nerd Font
bold_italic_font  BlexMono Nerd Font
