term xterm-kitty

include catppuccin-macchiato.conf

# font
font_family         FiraCode Nerd Font
bold_font           auto
italic_font         IBM Plex Mono
bold_italic_font    IBM Plex Mono
font_size           12.0
