[general]
live_config_reload = true

[window]
padding = { x =5, y = 5 }
dynamic_padding = true

[font]
normal = { family = "FiraCode Nerd Font" }
italic = { family = "IBM Plex Mono", style = "Italic" }
bold_italic = { family = "IBM Plex Mono", style = "Bold Italic" }

[terminal]
shell = { program = "tmux", args = ["new", "-A", "-s", "alacritty"] }

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
