[config]
reload_apps = true

[config.wallpaper]
command = "hyprctl"
arguments = ["hyprpaper", "wallpaper", ","]
set = true

## Templates
[templates.fuzzel]
input_path = './templates/fuzzel.ini'
output_path = '~/.config/fuzzel/matugen.ini'

[templates.kitty]
input_path = './templates/kitty.conf'
output_path = '~/.config/kitty/matugen.conf'

# GTK
[templates.gtk3]
input_path = './templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = './templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'
