preload = $HOME/wallpapers/Astronaut.png
preload = $HOME/wallpapers/Houses.png
preload = $HOME/wallpapers/View_of_Dresden_by_Moonlight.jpg

ipc = true

wallpaper = ,$HOME/wallpapers/View_of_Dresden_by_Moonlight.jpg
