wallpaper {
  monitor =
  path = $HOME/wallpapers/Astronaut.png
  fit_mode = cover
}
wallpaper {
  monitor =
  path = $HOME/wallpapers/Houses.png
  fit_mode = cover
}
wallpaper {
  monitor =
  path = $HOME/wallpapers/View_of_Dresden_by_Moonlight.jpg
  fit_mode = cover
}

ipc = true
splash = false
